### ISSUE TITLE
Create battery interface board prototype

### ISSUE THREAD

**Issue by griswaldbrooks** [victoriarobotics/victoria_electrical#1]
Make board that the batteries plug into, as well as having the alarm and LED voltage monitor.
The output of this board will be unregulated voltage.

**Comment by ralphhipps** [comment]
if we're using LIPOs, we might just want to use these:

https://smile.amazon.com/dp/B00SCJOITA/ref=wl_it_dp_o_pC_nS_ttl?_encoding=UTF8&colid=2NDVLRDKF1ORA&coliid=IJ8MTOJ0SRNJL

**Comment by griswaldbrooks** [comment]
I got an alarm very similar to that and a voltage indicator but as seperate units.

**Comment by griswaldbrooks** [comment]
Dropping in favor of #3
