### ISSUE TITLE
Integrate IMU into Teensy circuit

### ISSUE THREAD

**Issue by markwomack** [victoriarobotics/victoria_electrical#10]

**Comment by markwomack** [comment]
Note that the IMU will be controlled and connected via I2C on the Teensy, which (usually) requires pullup resistors on SDL anf SCL.  So, don't forget to do that on the circuit when integrating.

**Comment by markwomack** [comment]
Maybe we should have a I2C bus for SDL and SCL for future I2C expansion.

**Comment by griswaldbrooks** [comment]
The IMU being used is this:
Pololu MinIMU-9 v5
https://www.pololu.com/product/2738

**Comment by markwomack** [comment]
Circuit is integrated, tested circuit with code to access and display IMU data for accelerometer, gyro, and magnetometer.
