### ISSUE TITLE
Integrate GPS breakout board and FTDI board

### ISSUE THREAD

**Issue by markwomack** [victoriarobotics/victoria_electrical#11]
The board will be connected to the Upboard via USB, which will also supply the power for the GPS/FTDI circuit.  But the GPS and FTDI need to be integrated, translating the GPS serial output to the USB.

**Comment by griswaldbrooks** [comment]
The FTDI board had it's pins flipped and installed in the interface board. Needs to be wired.
FTDI model was https://www.amazon.com/HiLetgo-Ft232rl-Serial-Adapter-Arduino/dp/B00IJXZQ7C/ref=redir_mobile_desktop?_encoding=UTF8&psc=1&ref_=ya_aw_od_pi

**Comment by markwomack** [comment]
Circuit between FTDI and GPS boards completed.  Need to test with integration to make sure it works as expected.

**Comment by griswaldbrooks** [comment]
Tested.
