### ISSUE TITLE
Figure out RC vs Autonomous switching

### ISSUE THREAD

**Issue by markwomack** [victoriarobotics/victoria_electrical#17]
We need to be able to switch between RC and "autonomous" mode.  Right now the TRex has a jumper we can use to determine which one is used, but the documentation suggests that "channel 5" can be used to switch modes.  This would also make a good remote "dead man's switch".

**Comment by griswaldbrooks** [comment]
Test channel 5

**Comment by griswaldbrooks** [comment]
Removed RC remote. Going to use keyfob input going into Teensy.
