### ISSUE TITLE
Build Teensy Interface Board

### ISSUE THREAD

**Issue by griswaldbrooks** [victoriarobotics/victoria_electrical#4]
Need board that the Teensy and all the things the teensy needs can plug into.
Will also have the 5V rail for computer.

**Comment by griswaldbrooks** [comment]
@griswaldbrooks Need to add connector part numbers

**Comment by griswaldbrooks** [comment]
Here are the vertical locking connectors for the encoders, power, and serial.

- 4 Pin
  - WM4802-ND
  - http://www.digikey.com/product-detail/en/molex-llc/0705430003/WM4802-ND/114923

- 3 Pin
  - WM4801-ND
  - http://www.digikey.com/product-detail/en/molex-llc/0705430002/WM4801-ND/114919

- 2 Pin
  - WM4800-ND
  - http://www.digikey.com/product-detail/en/molex-llc/0705430001/WM4800-ND/114915

**Comment by griswaldbrooks** [comment]
Female headers for Teensy
- S7057-ND
- http://www.digikey.com/product-detail/en/sullins-connector-solutions/PPPC241LFBN-RC/S7057-ND/810196

**Comment by markwomack** [comment]
Circuit is soldered according to current requirements.  Room for future growth.

![20170128_172805](https://cloud.githubusercontent.com/assets/23406339/22908722/e4b01d50-f204-11e6-9778-857f390f2a72.jpg)
![20170211_162552](https://cloud.githubusercontent.com/assets/23406339/22908723/e4b061a2-f204-11e6-853c-346824230979.jpg)
![20170211_162605](https://cloud.githubusercontent.com/assets/23406339/22908724/e4b04cbc-f204-11e6-986e-d8ab957456bf.jpg)

**Comment by markwomack** [comment]
The base board is built.  I am closing this one and creating bugs for remaining, specific issues.
