### ISSUE TITLE
Install New Mains Power Switch

### ISSUE THREAD

**Issue by griswaldbrooks** [victoriarobotics/victoria_electrical#5]

**Comment by griswaldbrooks** [comment]
Installed.

**Comment by griswaldbrooks** [comment]
Switch from the outside.
![20170204_230120 1](https://cloud.githubusercontent.com/assets/390783/22624548/09e83828-eb34-11e6-906c-6177cd3a0a0b.jpg)

New switch can be seen installed in the lower left hand corner.
![20170204_230052](https://cloud.githubusercontent.com/assets/390783/22624551/2ea0845e-eb34-11e6-9df4-4df113401451.jpg)

**Comment by griswaldbrooks** [comment]
The switch was put in by opening up a hole a little bit in the existing rear port. As the original hole was square, there were some gaps which were closed by installing a washer and o-ring on the inside (non-weather facing) of the robot. The boot nut was tightened slightly, but the cramped space made it difficult to tighten fully.

**Comment by ralphhipps** [comment]
looks good!!!


Ralph

>+<
 |    /\
 |___/  \
 [_@_]   `<
 O O O          IRS!
------------------------------------------------------------------------------------
In the twenty-first century, the robot will take the place
which slave labor occupied in ancient civilization.
 -- Nikola Tesla
------------------------------------------------------------------------------------
