### ISSUE TITLE
Get wifi and Upboard on victoria

### ISSUE THREAD

**Issue by griswaldbrooks** [victoriarobotics/victoria_electrical#8]

**Comment by markwomack** [comment]
I think this is addressed?

**Comment by griswaldbrooks** [comment]
Yes. Upboard is now powered by Teensy circuit and wifi is provided by TP-Link TLWR802N set up in hotspot mode so we can connect to the robot and the robot can connect to another wifi, simultaneously. The AP name is victoria-tplink with the same password.
